faq_list = [
    {
        "question": "Application Process",
        "answer": (
            "The application process consists of the following steps: Step 1: Registering on the site by clicking the link 'http://admissions.keralauniversity.ac.in' and providing basic information (name, date of birth, and community).Step 2: Enter personal details, marks/CGPA of qualifying examination (up to VI semester for B.Tech/B.E.), and select programme options. Step 3: Pay the registration fee online only. Step 4: Upload photograph and signature. Step 5: Verify the application. Step 6: Take a printout of the application. You can submit it from any computer with Internet access within the specified schedule. Note: The registration fee once remitted will not be refunded under any circumstances."
        )
    },
    {"question": "What is the entrance exam?","answer": "The entrance examination is a mandatory entry requirement for Non-GATE candidates.The exam consists of 100 multiple-choice questions covering subject knowledge and logical/numerical reasoning, and is conducted for a maximum of 2 hours. The medium of examination is English."},
    {"question":"Courses of Computer Science department", "answer": "The Department of Computer Science offers an M.Tech in Computer Science with a specialization in Digital Image Computing, with an intake capacity of 18 seats."},
    {"question":"Fees of Computer Science department","answer":"The fee for M.Tech Computer Science (with Specialization in Digital Image Computing) is Rs.19845/- (including caution deposit) for general candidates. Sponsored candidates will pay Rs.15750/- per year in addition to the normal fee."},
    {"question":"Eligibility of Computer Science department","answer":"For M.Tech Computer Science with Specialization in Digital Image Computing at the University of Kerala, the eligibility criteria is as follows: * A Bachelor's degree in Engineering / Technology with at least 55% marks in one of the following branches: Computer Science and Engineering / Information Technology / Electronics Engineering / Electrical Engineering from the University of Kerala or equivalent recognized degree of a recognized University. * Preference will be given to candidates who have qualified GATE. * The candidates should have a First Class Master’s degree in Computer Science / Computer Application from the University of Kerala or equivalent recognized degree of a recognized University."},
    {"question":"Courses of Futures Studies department","answer":"The Department of Futures Studies offers an M.Tech in Technology Management with a total of 15 seats."},
    {"question":"Fees of Futures Studies department","answer":"The fees for M.Tech Technology Management (Futures Studies) is Rs. 8160/-. For Sponsored candidates, the fees is Rs. 21660/-."},
    {"question":"Eligibility of Futures Studies department","answer":"The Department of Futures Studies offers an M.Tech in Technology Management, with a total of 15 seats. The eligibility criteria for this programme is a B.Tech Degree or equivalent in any branch of Engineering / Technology with at least 55% marks from any of the recognized Universities in India. Preference will be given to candidates who have qualified GATE."},
    {"question":"Courses of Optoelectronics department","answer":"The Optoelectronics department offers an M.Tech in Electronics and Communication, specializing in Optoelectronics and Optical Communication, with 18 seats available."},
    {"question":"Fees of Optoelectronics department","answer":"The fees for the M.Tech Electronics and Communication (Optoelectronics and Optical Communication) department is Rs.26662/-. For Sponsored candidates, the fee is Rs.15750/- per year in addition to the normal fee."},
    {"question":"Eligibility of Optoelectronics department","answer":"The M.Tech Electronics and Communication (Optoelectronics and Optical Communication) programme offered by the Department of Optoelectronics requires at least a second class BE/B.Tech or equivalent degree with 55% marks in Electronics/Electrical and Electronics/Electronics and Communication Engineering, Applied Electronics and Instrumentation or M.Sc. Degree in Physics/Applied Physics/Electronic Science or Electronics from the University of Kerala or equivalent. Preference will be given to candidates who have qualified GATE."}  
      ]
